#!/bin/sh

mvn -DprocessDependencyManagement=false \
    versions:display-parent-updates \
    versions:display-dependency-updates \
    versions:display-plugin-updates \
    versions:display-property-updates

