#!/bin/bash -ue

if [ "$#" -eq 1 ]; then
  cmd=$1
else
  echo "Usage: $0 <cmd>"
  echo
  echo "Der Parameter ist entweder ein Plugin:Goal wie 'compiler:testCompile' oder eine Phase wie 'install'."
  exit 1
fi

set -x
mvn help:describe -Dcmd=$cmd -Ddetail=true
