FROM alpine:edge
MAINTAINER cb@lathspell.de
RUN apk add --no-cache openjdk8
# https://www.baeldung.com/dockerizing-spring-boot-application - Unlimited Strength Jurisdiction Policy
# COPY files/UnlimitedJCEPolicyJDK8/* /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/
