package de.lathspell.test;


import static java.util.Arrays.asList;

import org.hamcrest.CoreMatchers;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import de.lathspell.test.model.Person;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("/internals.xml")
public class InternalsTest {

    @Autowired
    private ApplicationContext context;

    @Autowired
    private Person anon;
    
    @Test
    public void testAnonymousBean() {
        // Injecting an anonymous bean does work if the type is enough to qualify it
        assertThat(anon.getFullName(), is("Frank Foo"));
        
        // The bean has an autogenerated name
        assertThat(asList(context.getBeanDefinitionNames()), CoreMatchers.hasItem("de.lathspell.test.model.Person#0"));
    }
}
